### ISSUE TITLE
Port Microsoft.AspNet.WebApi.Core to support .NET Standard 2.0

### ISSUE THREAD

**Issue by eriawan** [aspnet/AspNetWebStack#134]
# Problem

Current Microsoft.AspNet.WebApi.Core (a.k.a. [System.Web.Http in the code](https://github.com/aspnet/AspNetWebStack/tree/master/src/System.Web.Http)) release (5.2,4) is targeted to .NET 4.5, although it depends on Microsoft.AspNet.WebApi.Client v. 5.2.4 that supports .NET Standard 2.0 nicely. 
It is quite problematic to use Microsoft.AspNet.WebApi.Core nuget in a .NET Standard 2.0 project. It may compile, but the resulting assembly will not run. 
Also looking at the current code in master branch, the csproj is still using .NET 4.5 and VS 2012 csproj model.

# Suggestion

Port Microsoft.AspNet.WebApi.Core to support multiple TFM of .NET Standard 2.0 _and_ .NET Framework 4.6.1, 4.7.1 instead of the existing TFM of unsupported .NET Framework 4.5.

If this got accepted, I'd start a PR to refactor and retarget this Microsoft.AspNet.WebApi.Core to update this to support multiple TFM of:

-  .NET Standard 2.0 (hence this will be easy to be used in .NET FW 4.7.1 project)
- .NET Standard 1.6 (to ease compatibility with .NET FW 4.6.1 project)
- .NET Framework 4.6.1 (for non- .NET Standard project)

I welcome feedback.

cc @Eilon

**Comment by mkArtakMSFT** [comment]
Hi @eriawan. Thank you for your suggestion. Unfortunately we do not have any plans to migrate WebApi to .NET Standard. We have no plans to support ASP.NET Web API on anything but .NET Framework.
If you are trying to target .NET Core, we'd recommend you to switch to ASP.NET Core.

**Comment by sksallaj82** [comment]
Is there a way to start plans for this? I'm using Xamarin Forms for the basis of my app project, and netstandard is the framework  that compatible with this sharing of code base. You can't simply switch to ASP.NET core and expect it to work, because the project throws an error of the compatibility between mono android (for example) and asp core 2.0. I need my netstandard library to communicate with the server. What I have to do instead is write my own kind of restclient app (or 3rd party libraries) with http service calls using System.Net.Http; would be a lot easier/nicer if it was wrapped up as a web api package built in.
