### ISSUE TITLE
Where to find YSOD source

### ISSUE THREAD

**Issue by memark** [aspnet/AspNetWebStack#144]
I'm trying to locate the source code or markup for the classic YSOD "Server Error in..." exception handling page. I've tried searching for various phrases, but cannot find it. Is this the right repo?

**Comment by Eilon** [comment]
Hi @memark , the ASP.NET YSOD code is in the System.Web library. You can find the ".NET Reference Source" of System.Web here: https://github.com/Microsoft/referencesource/tree/master/System.Web

I *think* that this is the main class for it: https://github.com/Microsoft/referencesource/blob/master/System.Web/ErrorFormatter.cs

But it's been the better part of a decade since I debugged through that. Best of luck 😄
