### ISSUE TITLE
Where is the System.Net.Http.Formatting nuget package?

### ISSUE THREAD

**Issue by wind-rider** [aspnet/AspNetWebStack#169]
I see that there is worked on a [System.Net.Http.Formatting version for .Net Standard 2.0](https://github.com/aspnet/AspNetWebStack/blob/master/src/System.Net.Http.Formatting.NetStandard/System.Net.Http.Formatting.NetStandard.csproj), but I can't seem to find the official nuget package for that supporting .Net Standard 2.0.

The result of people not being able to find it is that there are around [10 nuget packages that are self-compiled copies of your package](https://www.nuget.org/packages?q=System.Net.Http.Formatting).

Could you please let me know what the status is or point me at the place to find it? Has it been replaced by something else?

**Comment by wind-rider** [comment]
Slightly related question - isn't this a package that could be made independent of asp.net - as it contains extensions to System.Net.Http?

**Comment by wind-rider** [comment]
I found out that it has been replaced by [Microsoft.AspNet.WebApi.Client](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client/), so this issue can be closed.

Hopefully this GitHub issue will point people to the right nuget package.

**Comment by Azure3bt** [comment]
I got a problem with this, I've NuGet package use netstandard that using Microsoft.AspNet.WebApi.Client as 5.2.7 version and use that package in other clients got an error that said "Could not find System.Net.Http.Formatting 5.2.7" but this version not available and I use System.Net.Http.Formatting 5.2.3 instead of Microsoft.AspNet.WebApi.Client as 5.2.7 then error gone
