### ISSUE TITLE
JsonResult didn't respect the ValueTuple names

### ISSUE THREAD

**Issue by anirudhagupta** [aspnet/AspNetWebStack#180]
public (string name, string email) Foo()
        {
            return (name: "Anirudha", email: "Gupta");
        }

        public JsonResult Test()
        {
            return Json(Foo(), JsonRequestBehavior.AllowGet);
        }

when  I run this code it's give me {"Item1":"Anirudha","Item2":"Gupta"}
I believe that it should be name and email instead of item1 and item2.

**Comment by dougbu** [comment]
@anirudhagupta this is a rather significant ask because [`ValueTuple`](https://docs.microsoft.com/en-ca/dotnet/api/system.valuetuple?view=netframework-4.7.2) is not available in full .NET Framework versions before 4.7. Thus extending [`JsonResult` ](https://github.com/aspnet/AspNetWebStack/blob/master/src/System.Web.Mvc/JsonResult.cs) to support it would require bumping our target framework way up from its current 4.5.2. We are not likely to make such a change -- back-compatibility is too important.

**Comment by anirudhagupta** [comment]
@dougbu  no issue then.
