### ISSUE TITLE
ASP.NET WebApi OWIN reads entire Stream for HEAD request when using HttpMessageResult with StreamContent

### ISSUE THREAD

**Issue by binki** [aspnet/AspNetWebStack#189]
If I return an `HttpMessageResult` from an `ApiController` handler and run this in IISExpress, the client correctly receives only the headers very quickly and omits the entity body as expected. However, the `Stream` in the `StreamContent` is fully spooled. Instead, the WebAPI and OWIN adapters for it should not spool the `Stream` in the `StreamContent`.

When handling a `HEAD` request, I want to place the real `Stream` resource in the `HttpMessageResult`. This way, the framework can automatically propagate information such as `Content-Type` from the `StreamContent` and correctly calculate `Content-Length` by checking `Stream.Length`. However, I do not want the server to spend time spooling through the `Stream` and keep resources open uselessly.

To work around this in my project, I am creating a crippled `Stream` wrapper which overrides `CopyToAsync()` with a no-op (for when I’m running with the System.Net.Http-4.3.3 NuGet package [which uses `CopyToAsync()`](https://github.com/dotnet/corefx/blob/4f04db9bce6f2dd92d5d2edc9f7b89d005e26856/src/System.Net.Http/src/System/Net/Http/StreamToStreamCopy.cs#L34)) and overrides `Read()` with a no-op that returns 0 (for when I’m running on .NET Framework) [which uses `Read()` (`BeginRead()` roughly calls `Task.Run(() => Read())`](https://github.com/nuxleus/WCFWeb/blob/b6c260a3b3c7cb8a908d3c71cf817722a6de2435/WCFWebApi/Http/Src/Microsoft.Net.Http/StreamToStreamCopy.cs#L97) and `ReadAsync()` in case .netfx or other things ever decide to use that in the future. Then I am checking if the request is a `HEAD` and conditionally wrapping my response in that stream:

```csharp
/// <summary>
///   Builds a <see cref="StreamContent"/> appropriately depending on the request type.
/// </summary>
StreamContent BuildStreamContent(
    Stream stream)
{
    // With OWIN+WebApi, it will call StreamContent.CopyToAsync() (System.Net.Http NuGet)
    // or all the Read() (.netfx) even if it is a HEAD request. It will actually spool the entire resource.
    // Instead, we need to not spool the entire resource to to the right thing. Otherwise,
    // this request handler will run longer and keep a file handle open unnecessarily.
    if (Request.Method == HttpMethod.Head)
    {
        stream = new IgnoreCopyToWrappingStream(stream);
    }
    return new StreamContent(stream);
}
```

I shouldn’t need to do this in my code just to support `HEAD` requests properly.

Please update `System.Web.Http.Owin.HttpMessageHandlerAdapter` and `System.Web.Http.WebHost.HttpControllerHandler` to avoid copying the `HttpContent` response body to the target for `HEAD` requests and only ensure that headers are sent and the content `Dispose()`d.

I understand that not calling `HttpContent.CopyToAsync()` may be considered a breaking change. It is possible that a developer would place side effects in their implementation of `HttpContent.CopyToAsync()` and expect those side-effects to happen even for `HEAD` requests. I am not sure how this issue could be resolved. However, I expect most people to put such side effects directly in their controller instead and, also, `HEAD` is expected to be more pure than `GET`, so I think this change may be justifiable.

I have provided a demo/repro repro: https://github.com/binki/StreamStreamedDuringHeadRequest . It provides a logging `Stream` implementation and the `README` shows how to use demo to reproduce the issue as well as sample output.

**Comment by dougbu** [comment]
@binki while it's true `HttpMessageHandlerAdapter` and `HttpControllerHandler` do not special-case response content in the case of a HEAD request, it's not something we can change at this point.

I suggest you special-case HEAD requests in your action instead of introducing `IgnoreCopyToWrappingStream`. The action should set the `Content-length` header but use an empty result  i.e. not include `StreamContent`.

---- 

> I understand that not calling `HttpContent.CopyToAsync()` may be considered a breaking change

Yes.

**Comment by jijohn14** [comment]
@dougbu Consider the case when there is no route for the HEAD verb in server. Http client fails with `System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host`.

Owin logs the below exception via exception logger which I believe is because Owin tries to write response content:  `{"Message":"The requested resource does not support http method 'HEAD'."}`
```
System.Net.ProtocolViolationException: Bytes to be written to the stream exceed the Content-Length bytes size specified.
   at System.Net.HttpResponseStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.<WriteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContent.<CopyToAsyncCore>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Owin.HttpMessageHandlerAdapter.<SendResponseContentAsync>d__20.MoveNext()] 
```

Owin should be handling this by having fixes like @dougbu  suggested to avoid `HttpContent.CopyToAsync()`. Thoughts?

**Comment by dougbu** [comment]
@jijohn14 sounds like your issue belongs in the https://github.com/aspnet/AspNetKatana repo.

**Comment by jijohn14** [comment]
@dougbu There is an issue in Katana https://github.com/aspnet/AspNetKatana/issues/218 which ultimately lead to an issue here: https://github.com/aspnet/AspNetWebStack/issues/182.

**Comment by jijohn14** [comment]
@binki It is similar. For your issue, the response content shouldn't be accepted by OWIN rather be disposed. In my case OWIN shouldn't be adding httperror content.  

https://github.com/aspnet/AspNetWebStack/issues/182 is the issue I have because Owin will add a response content for HEAD request. I am able to work around it by making the context = null in DelegatingHandler. https://github.com/aspnet/AspNetKatana can do the same but the question is why OWIN behaves like this.
