### ISSUE TITLE
IHtmlContent not rendering as HtmlString in MVC 5.2.7?

### ISSUE THREAD

**Issue by kendallb** [aspnet/AspNetWebStack#290]
I am in the process of migrating our code slowly over to .net Standard 2.0 for our supplemental libraries, so that we can eventually migrate our huge application stack over to ASP.Net Core and .Net 5. We have been using HtmlTags for years, and I recently updated it to the latest version that uses .net Standard 2.0, and since it is now targetting .net code it no longer implemented IHtmlString in the HtmlTag class. Rather it implements IHtmlContent, which is the new ASP.net Core version of that interface.

Well needless to say, when we use this library it does not work as it renders the HTML encoded onto the page, as it does not recognize it should be rendered as raw HTML. 

So when the page writes an object, it does it like so:

``` C#
    /// <summary>Writes the specified object as an HTML-encoded string.</summary>
    /// <param name="value">The object to encode and write.</param>
    public override void Write(object value) => WebPageExecutingBase.WriteTo(this.Output, value);
```

which then writes it to the output like so:

``` C#
    /// <summary>Writes the specified object as an HTML-encoded string to the specified text writer.</summary>
    /// <param name="writer">The text writer.</param>
    /// <param name="content">The object to encode and write.</param>
    public static void WriteTo(TextWriter writer, object content) => writer.Write(HttpUtility.HtmlEncode(content));
```

So the problem is this is how HttpUtility.Encode() is implemented:

``` C#
    /// <summary>Converts an object's string representation into an HTML-encoded string, and returns the encoded string.</summary>
    /// <param name="value">An object.</param>
    /// <returns>An encoded string.</returns>
    public static string HtmlEncode(object value)
    {
      if (value == null)
        return (string) null;
      return value is IHtmlString htmlString ? htmlString.ToHtmlString() : HttpUtility.HtmlEncode(Convert.ToString(value, (IFormatProvider) CultureInfo.CurrentCulture));
    }
```

Unfortunately there is nothing in there that knows about IHtmlContent. I don't see any updated packages for any of the related packages like Microsoft.AspNet.Mvc (5.2.7 is the latest), so there is no easy solution for this problem that I can think of. Best I can come up with at the moment is to derive my own view page for all our Razor views, and override the write function in there to understand IHtmlContent? It would work (and we already have our own custom base class to handle IoC), but it does mean if someone forgets to use it, stuff breaks.

But really to support allowing folks to slowly migrate their tech stacks over to .net standard, and still have that code work with MVC 5.2.7, there really needs to be something that understands IHtmlContent and treats it the same as IHtmlString?

**Comment by kendallb** [comment]
So this is my solution for the moment, but it really needs to be implemented directly in the ASP.net MVC code IMHO:

``` C#
        /// <summary>
        /// Writes the specified object as an HTML-encoded string.
        /// </summary>
        /// <param name="value">The object to encode and write.</param>
        public override void Write(
            object value)
        {
            if (value is IHtmlContent htmlString) {
                htmlString.WriteTo(Output, HtmlEncoder.Default);
            } else {
                base.Write(value);
            }
        }
```

**Comment by dougbu** [comment]
@kendallb what is your issue with your workaround❔

I'm not sure how we could address your mixed scenario in aspnet/AspNetWebStack. Introducing dependencies on ASP.NET Core packages would break compatibility. Worse, recent Microsoft.AspNetCore.Html.Abstractions.dll (the assembly containing `IHtmlContent`) versions build for `net5.0` only and do not ship as a package i.e. outside the `net5.0` shared framework; it's not usable everywhere `HttpUtility` or `WebPageExecutingBase` are.

**Comment by kendallb** [comment]
Well the core issue is that to migrate from .net 4.8 to .net 5.0, we also need to migrate to ASP.net core. The stepping stone for this is migrating all our dependent libraries to .net standard 2.0 (since 2.1 is not compatible with 4.8). I was really hoping to target .net 5.0 in our libraries, but that cannot be consumed by .net 4.8 either.

So the problem we run into is libraries that support '.net standard 2.0' and are compatible with .net 4.8, like HtmlTags, no longer actually work with .net 4.8 even though it would appear it should. The project literally no longer has a .net 4.8 library (it's .net standard 2.0):

https://www.nuget.org/packages/HtmlTags/

Hence folks like me come along and it does not work properly. You need to make the tooling for MVC 5.2.7 support .net standard libraries, which would mean having it understand IHtmlContent coming from .net standard libraries. 

So sure, I have a solution for us in the interim to work around this, so I am able to move forward, but I imagine others using HtmlTags who blindly update to the latest version are going to be quite surprised if they are still using ASP.net MVC 5.2

**Comment by kendallb** [comment]
BTW, I am also not clear on how to you can solve the problem, but I do think it's quite a big problem for folks still on the old tech stack, as library developers move their stuff over to .net core and .net 5.

**Comment by kendallb** [comment]
Well, my workaround does not work either because it does not work inside Razor helpers(). I don't see any feasible way to work around it, as it it literally writes directly to the helper stream via a static function:

``` C#
    /// <summary>Writes the specified object as an HTML-encoded string to the specified text writer.</summary>
    /// <param name="writer">The text writer.</param>
    /// <param name="content">The object to encode and write.</param>
    public static void WriteTo(TextWriter writer, object content) => writer.Write(HttpUtility.HtmlEncode(content));
```

So basically unless regular MVC can be taught how to support IHtmlContent, or somehow IHtmlString is added to .net standard, there is no way to port our code in bits. It's going to be an all or nothing deal, which probably means a couple of months of work :(

**Comment by dionrhys** [comment]
I think the issue here is that HtmlTags 8.x has [removed support](https://github.com/HtmlTags/htmltags/releases) for ASP.NET and is now only compatible with ASP.NET Core:

> **8.1.1** Removes all support for classic ASP.NET, only targeting ASP.NET Core going forward. Adds support for ASP.NET 5.

This repo is for the older ASP.NET web stack and wouldn't contain new ASP.NET Core functionality like `IHtmlContent`. You'll need to stay on HtmlTags 7.x it seems, if you want to use it in an ASP.NET MVC project.

If you have a class library that uses HtmlTags and you intend to have both your existing ASP.NET project and a new ASP.NET Core project reference it, you might be able to multi-target frameworks and have [conditional package references](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#adding-a-packagereference-condition) on that class library so that you reference HtmlTags 7.x on .NET Framework (4.x) and reference HtmlTags 8.x on .NET Core / 5.

If there are breaking API changes between those versions, you might need to have `#if` conditionals in the code that behaves differently based on whether you're building for .NET Framework or .NET Core / 5.

Migration from ASP.NET to ASP.NET Core can be really helped by moving business logic away from the ASP.NET project and into separate projects with no ties to any ASP.NET code (i.e. not touching anything having `System.Web` or `Microsoft.Web` in the namespace). Unfortunately, HtmlTags is a project that has a strong dependency on the underlying web framework, which requires more end-user effort when upgrading between the two frameworks.

**Comment by kendallb** [comment]
It's been a while since I looked into this, but the core problem as I recall is that because HtmlTags is built to target .NET Standard 2.0, and THAT is a problem. Because if you pull in 8.1.1 into your legacy ASP.NET MVC application running on .NET 4.8 or earlier, it will no longer work correctly. So 7.0.4 is the last version that is useable for folks using the original .NET framework.

To fix this I would suggest that all 8.x releases DO NOT target .NET Standard 2.0 at all. Instead it should only target NETCoreApp 3.1 and net5.0, as then folks cannot accidently bring in a package that will not work. They would end up being forced to remain on 7.0.4 which is fine, as that version will work.

Supporting a cross platform target when the code compiled into it is not actually compatible at all is the problem. Another solution if you really wanted to target .NET Standard, would be to target something > 2.0 which will not be compatible with .NET Framework and would also solve the problem that you would not be able to include the package in your project.

**Comment by dionrhys** [comment]
> To fix this I would suggest that all 8.x releases DO NOT target .NET Standard 2.0 at all. Instead it should only target NETCoreApp 3.1 and net5.0, as then folks cannot accidently bring in a package that will not work. They would end up being forced to remain on 7.0.4 which is fine, as that version will work.

The problem with this is that ASP.NET Core 2.1 is [supported long term for .NET Framework](https://dotnet.microsoft.com/platform/support/policy/dotnet-core):

> ### ASP.NET Core 2.1 on .NET Framework
>
> Support for ASP.NET Core 2.1 on .NET Framework matches the ASP.NET Support policy for other package-based ASP.NET frameworks. The complete list of packages covered by this policy can be seen in ASP.NET Core 2.1 Supported Packages.

https://dotnet.microsoft.com/platform/support/policy/aspnet:

> To help facilitate migrating applications to ASP.NET Core on .NET Core, the following ASP.NET Core 2.1 (latest patched version only) packages will be supported on the .NET Framework and follow the support cycle for those .NET Framework versions. ASP.NET Core 2.1 is defined as "Tools" in the Microsoft Support Lifecycle Policy. A "Tool" requires a minimum of 12 months notification prior to the end of support. For more information, please see this KB Article.

https://dotnet.microsoft.com/platform/support/policy/aspnetcore-2.1

I can see that HtmlTags [references ASP.NET Core 2.0 when targetting .NET Standard 2.0](https://github.com/HtmlTags/htmltags/blob/53781b0bf87c2fc859bf0d3ef26df1c749fc5631/src/HtmlTags/HtmlTags.csproj#L35), so 8.x _should_ already be fully compatible with ASP.NET Core running on the .NET Framework, and I think targetting .NET Standard 2.0 is fine for that (HtmlTags expects you're using ASP.NET Core on .NET Framework instead of ASP.NET).

_I personally use ASP.NET Core 2.1 running on .NET Framework 4.7.2 at work for web apps that unfortunately still require legacy .NET Remoting tech (which will never be supported in .NET Core) to communicate with some internal services._

But yeah I think any issue here is something that'll need to be fixed on HtmlTags's side, and wouldn't be a change for the ASP.NET web stack.

**Comment by kendallb** [comment]
Right, totally forgot that .NET Standard 2.1 is what we need to support ASP.NET Core on .NET Framework. It's the stepping stone.

This this could be fixed in HtmlTags by not supporting it, but the libraries are already out there in the wild. My original request was to somehow get the legacy ASP.NET framework to somehow know about and support IHtmlContent so .NET Framework code ingesting .NET Standard 2.1 or lower libraries can work correctly. Stuff will just silently fail until you get your code recompiled as ASP.NET Core, which is the process we are moving towards at the moment.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us and sharing your use case and scenarios. After some discussion about this issue we've concluded that we won't be able to do much here. Closing as no further action is pending.

**Comment by kendallb** [comment]
Yeah, not sure what a good solution is, but it's gonna bite a lot of folks in the ass (just like it did for me). We are still not migrated to .net core, so still have to deal with this at some point. Losing access to HttpContext.Current means lots of the library code we use does not work :(. So still porting that ...
