### ISSUE TITLE
Value does not fall within the expected range

### ISSUE THREAD

**Issue by cblaze22** [aspnet/AspNetWebStack#321]
I have this weird issue using Controller.Url.Action, where the Controller is stored in a variable.  My values are fine in terms of integers.

[Stack Overflow](https://stackoverflow.com/questions/71482764/value-does-not-fall-within-the-expected-range-with-t4mvc-in-asp-net-mvc-site)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Given the information you've shared including the details in StackOverflow it doesn't immediately point out to an issue in our repo. If you're convinced that's the case, please share a reliable repro project hosted as a public GitHub repo, so that we can investigate this further.

Also, the comments in your StackOverflow post have some suggestions which it seems you haven't tried / responded to. Specifically the comment from [Chrotenise](https://stackoverflow.com/users/1885199/chrotenise) seems interesting to try.

Please note, that this code-path hasn't changed for years and we haven't received similar feedback in the past.

**Comment by cblaze22** [comment]
Yes I already did that Chrotenise did.  The values look fine.  I feel like something is caching, maybe some bad values went in somehow initially and every call after throws that error.  I can restart the site and it starts working fine again, very odd.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
