### ISSUE TITLE
System.Web.Mvc.HtmlHelper.RenderPartialInternal InvalidOperationException

### ISSUE THREAD

**Issue by d-vs** [aspnet/AspNetWebStack#58]
A System.InvalidOperationException occurs when rendering a partial view by passing in the property of a view model to HtmlHelper.Partial, when that property is an uninitialized reference type (a null reference). The exception message takes the form:

The model item passed into the dictionary is of type '{type A}', but this dictionary requires a model item of type '{type B}'.

Type A above is the view model type, and type B is the type expected by the partial view.

I believe that this occurs because of line 527 in System.Web.Mvc.HtmlHelper

newViewData = new ViewDataDictionary(ViewData);

which attempts to initialize a new ViewDataDictionary using the HtmlHelper.ViewData, which refers to the view's model, not the model's property. Hence the type mismatch. This is incorrect and should be initialized using the null value passed in, as in line 538.

This is a duplicate of the bug I reported at https://connect.microsoft.com/VisualStudio/feedback/EditFeedback.aspx?FeedbackID=3140000

**Comment by dougbu** [comment]
It sounds like the partial view lacks an `@model` directive. If this is the case, please add that and see if the problem is resolved.

If that does not resolve your issue, please reopen and provide more information. Steps to reproduce or a small sample project (best in a GitHub repo) would be much appreciated.
