### ISSUE TITLE
Newtonsoft.Json specific assembly reference is breaking my projects

### ISSUE THREAD

**Issue by EdLichtman** [aspnet/AspNetWebStack#60]
Hello all,

I'm not sure if this is the right place, but I'm looking for the code-behind Microsoft.AspNet.WebApi. It seems that the reference to System.Net.Formatting makes a specific reference to Newtonsoft.Json, Version=6.0.0.0. I use bindingRedirects and it compiles, but at run-time if I try to hit the page I find myself in Dependency hell.

If you need Version 6.0.0.0, I suggest you set specificVersion to true to ensure that no one else finds themselves here after it compiles properly. If you don't need Version 6.0.0.0, Newtonsoft.Json is on version 10 now, could you please remove the specific reference details so that instead of saying reference="Newtonsoft.Json, Version 6.0.0.0...." It just says reference="Newtonsoft.Json"?

Or, please advise one what I should do to get out of dependency hell if no change is necessary.

**Comment by Eilon** [comment]
Hi @EdLichtman , it isn't clear to me exactly what the problem is. You should be able to update your dependency on NewtonSoft.Json to any version that is greater than or equal to the minimum requirement of 6.0.4. If any binding redirects are needed, NuGet will automatically create them when you update the package version.

If you're seeing a specific error, please tell us the exact steps you followed, plus copy/paste or screenshots of the exact errors you've seen.
